fix check

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -16,13 +16,15 @@ jobs:
         run: cargo binstall cargo-generate
       - name: Generate and build all templates
         run: |
-          for template_name in $(ls templates/); do
-            echo "$template_name"
-            template_name=$(basename "$template")
-            cargo generate --path "$template" --name "$template_name" --destination ./"$template_name" --force
-            cd "$template_name"
-            npx wrangler build || echo "Build failed for $template_name"
+          mkdir -p generated
+          for template in templates/*/; do
+              template_name=$(basename "$template")
+              echo "Generating $template_name"
+              cargo generate --path $template --name "$template_name" --destination ./generated --force
+              cd "generated/$template_name"
+              npx wrangler build || echo "Build failed for $template_name"
           done
+
   rustfmt:
     name: Formatter
     runs-on: ubuntu-latest
